version: '3.8'

services:
  postgres:
    container_name: nestjs-sequelize-postgis-jwt
    image: postgis/postgis
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_TOKEN: ${JWT_TOKEN}
      JWT_REFRESH: ${JWT_REFRESH}
      JWT_TOKEN_TTL: ${JWT_TOKEN_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
