export const SEQUELIZE = 'SEQUELIZE'
export const DEVELOPMENT = 'development'
export const TEST = 'test'
export const PRODUCTION = 'production'
export const PROPERTY_REPOSITORY = 'PROPERTY_REPOSITORY'
export const BOOKING_REPOSITORY = 'BOOKING_REPOSITORY'
